import { defineConfig } from "vite";
import path from "node:path";
import { readdir, stat, readFile, writeFile } from "node:fs/promises";
import { readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { Input, InputType, Packer } from "roadroller";
import ClosureCompiler from "google-closure-compiler";

import ect from "ect-bin";
import advzip from "advzip-bin";

export default defineConfig(({ command }) => ({
	plugins: [
		dds(),
		shader(command == "build"),
		...(command == "build" ? [closure(), roadroller(), zip()] : []),
	],
	build: {
		assetsDir: "",
		modulePreload: { polyfill: false },
		rolldownOptions: {
			output: {
				comments: true, // So closure can see them
			},
		},
	},
	resolve: {},
	server: {
		proxy: {},
	},
}));

var dds = () => ({
	name: "vite:dds",
	load: (id) =>
		/\.dds(?:\.gz)?$/.test(id)
			? `export default "${readFileSync(id).toString("base64")}";`
			: undefined,
});

var shader = (isBuild) => ({
	name: "vite:shader",
	transform: (code, id) => {
		if (!id.endsWith(".wgsl")) return;

		/*
		code = code.replace(/^#import "([^"]*)".*$/gm, (str) => {
			return '${await import("./' + str + '").then(m => m.default)}';
		}); 
		*/

		code = code.replace(/^#import "([^"]*)".*$/gm, (_, str) => {
			return readFileSync(path.resolve(path.dirname(id), str), "utf-8");
		});

		console.log(code);

		if (!isBuild) {
			code = code.replace(/^\s*\/\/.*$/gm, ""); // remove comments
			code = code.replace(/^\s*$/gm, ""); // remove empty lines
			code = code.replace(/^\s+/gm, ""); // remove leading whitespace
			code = code
				.replace(/\\/g, "\\\\")
				.replace(/`/g, "\\`")
				.replace(/\$\{/g, "\\${");
			return {
				code: `export default \`${code}\`;`,
				map: null,
			};
		} else {
			writeFileSync("./tmp.wgsl", code);
			const result = execFileSync("wgsl-minifier", [
				"--force",
				"./tmp.wgsl",
				"./tmp.out.wgsl",
			]);
			console.log(result.toString());
			code = readFileSync("./tmp.out.wgsl", "utf-8");
			return {
				code: `export default \`${code}\`;`,
				map: null,
			};
		}
	},
});

var roadroller = () => ({
	name: "vite:roadroller",
	transformIndexHtml: async (html, ctx) => {
		if (!ctx || !ctx.bundle) {
			return html;
		}

		let code;

		const bundleOutputs = Object.values(ctx.bundle);
		const javascript = bundleOutputs.find((output) =>
			output.fileName.endsWith(".js"),
		);
		const css = bundleOutputs.find((output) =>
			output.fileName.endsWith(".css"),
		);
		const otherBundleOutputs = bundleOutputs.filter(
			(output) => output !== javascript,
		);
		if (otherBundleOutputs.length > 0) {
			otherBundleOutputs.forEach((output) =>
				console.warn(`WARN Asset not inlined: ${output.fileName}`),
			);
		}

		let data = `(async () => {\n${javascript.code}\n})();`;
		if (false) {
			const options = {
				includeAutoGeneratedTags: true,
				removeAttributeQuotes: true,
				removeComments: true,
				removeRedundantAttributes: true,
				removeScriptTypeAttributes: true,
				removeStyleLinkTypeAttributes: true,
				sortClassName: true,
				useShortDoctype: true,
				collapseWhitespace: true,
				collapseInlineTagWhitespace: true,
				removeEmptyAttributes: true,
				removeOptionalTags: true,
				sortAttributes: true,
				minifyCSS: true,
			};

			const packer = new Packer(
				[
					{
						data,
						type: "js",
						action: "eval",
					},
				],
				options,
			);

			await Promise.all([
				packer.optimize(2), // Regular builds use level 2, but rr config builds use the supplied params
			]);

			const { firstLine, secondLine } = packer.makeDecoder();
			const runner = `${firstLine}\n${secondLine}`;
			code = runner;
		} else {
			code = data;
		}

		return html.replace(/<script.*?<\/script>/, `<script>${code}</script>`);
	},
});

var closure = () => ({
	name: "vite:closure",
	renderChunk: async (code, chunk, options) => {
		const tmpobj = { name: "tmp.js" };

		let WEBGPU_CONSTANTS = {
			"GPUBufferUsage.MAP_READ": 1,
			"GPUBufferUsage.MAP_WRITE": 2,
			"GPUBufferUsage.COPY_SRC": 4,
			"GPUBufferUsage.COPY_DST": 8,
			"GPUBufferUsage.INDEX": 16,
			"GPUBufferUsage.VERTEX": 32,
			"GPUBufferUsage.UNIFORM": 64,
			"GPUBufferUsage.STORAGE": 128,
			"GPUBufferUsage.INDIRECT": 256,
			"GPUBufferUsage.QUERY_RESOLVE": 512,

			"GPUTextureUsage.COPY_SRC": 1,
			"GPUTextureUsage.COPY_DST": 2,
			"GPUTextureUsage.TEXTURE_BINDING": 4,
			"GPUTextureUsage.STORAGE_BINDING": 8,
			"GPUTextureUsage.RENDER_ATTACHMENT": 16,

			"GPUShaderStage.VERTEX": 1,
			"GPUShaderStage.FRAGMENT": 2,
			"GPUShaderStage.COMPUTE": 4,
		};

		for (const [key, value] of Object.entries(WEBGPU_CONSTANTS)) {
			code = code.replace(new RegExp(`\\b${key}\\b`, "g"), value);
		}

		code = code.replace(/label`[^`]*`/g, "''");
		code = code.replace(/"label": '',/g, "");

		await writeFile(
			tmpobj.name,
			`
			
/** 
 * @define {boolean} 
 */
var DEBUG = true;
(async () => {\n${code}\n})();

		`,
		);

		const compiler = new ClosureCompiler({
			js: tmpobj.name,
			compilation_level: "ADVANCED",
			language_in: "ECMASCRIPT_2020",
			language_out: "ECMASCRIPT_2020",
			chunk_output_type: "ES_MODULES",
			externs: "externs.js",
			define: "'DEBUG=false'",
			warningLevel: "VERBOSE",
			assume_function_wrapper: true,
		});

		return new Promise((resolve, reject) => {
			compiler.run((exitCode, stdOut, stdErr) => {
				console.warn(stdErr);
				if (exitCode === 0) {
					stdOut = stdOut.replace(/\bconst\b/g, "let");
					stdOut = stdOut.replace(/^\(async\(\)=>{/g, "");
					stdOut = stdOut.replace(/}\)\(\);export{};\s*$/g, "");
					resolve({ code: stdOut });
				} else {
					reject(new Error(stdErr));
				}
			});
		});
	},
});

var zip = () => ({
	name: "vite:ect",
	writeBundle: async () => {
		try {
			const files = await readdir("dist/");
			const assetFiles = files
				.filter((file) => {
					return (
						file != "index.html" &&
						file != "index.zip" &&
						!file.endsWith(".js")
					);
				})
				.map((file) => "dist/" + file);

			const args = [
				"-strip",
				"-zip",
				"-10009",
				"dist/index.html",
				...assetFiles,
			];
			const result = execFileSync(ect, args);
			console.log("ECT result", result.toString());
			const advzipResult = execFileSync(advzip, [
				"-4",
				"-z",
				"dist/index.zip",
			]);
			console.log("advzip result", advzipResult.toString());
			const stats = await stat("dist/index.zip");
			console.log(
				"ZIP size",
				Math.round((stats.size / 1024) * 100) / 100,
				"KB",
			);
		} catch (err) {
			console.log("ECT error", err);
		}
	},
});
