export const OP_STROKE = 1,
	OP_VEC = 2,
	OP_VLOAD = 3,
	OP_VSTORE = 4,
	OP_FLOAD = 5,
	OP_FSTORE = 6,
	OP_PUSHI = 7,
	OP_MIRROR = 8,
	OP_FLIP = 9,
	OP_VSTORE3 = 10,
	OP_LOADP = 11,
	OP_JUMPIF = 12,
	OP_SIZE = 13;

export const COMMAND_NAMES = {
	"stroke": OP_STROKE,
	"vec": OP_VEC,
	"vload": OP_VLOAD,
	"vstore": OP_VSTORE,
	"vstore3": OP_VSTORE3,
	"fload": OP_FLOAD,
	"fstore": OP_FSTORE,
	"loadp": OP_LOADP,
	"jumpif": OP_JUMPIF,
	"size": OP_SIZE,
	"pushi": OP_PUSHI,
	"mirror": OP_MIRROR,
	"flip": OP_FLIP,
};
